<?php if ($this->pageCount > 1): ?>
    <div class="pagination pagination-small">
        <ul>
            <li>
                <?php if ($this->current != 1): ?>
                <a class="zf-green" href="<?= $this->url(null, array('page' => 1), true) ?>">«</a>
                <?php else: ?>
                    <a class="zf-green" href="<?= $this->url(null, array('page' => 1), true) ?>" class="disabled">«</a>
                <?php endif; ?>
            </li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li><a class="zf-green" href="<?= $this->url(null, array('page' => $page), true) ?>" class="btn"><?php echo $page; ?></a></li>
                <?php else: ?>
                    <li><a class="zf-green" style="color: black" href="#" class="btn disabled"><?php echo $page; ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <!-- Next page link -->

            <li>
                <?php if ($this->current != $this->pageCount): ?>
                    <a class="zf-green" href="<?= $this->url(null, array('page' => $this->pageCount), true) ?>">»</a>
                <?php else: ?>
                    <a class="zf-green" href="<?= $this->url(null, array('page' => 1), true) ?>" class="disabled">»</a>
                <?php endif; ?>
            </li>
        </ul>
    </div>
<?php endif; ?>