<div class="row">
    <div class="span10">
        <h2>Lista de posts</h2>
    </div>
    <div class="span2" style="text-align: right">
        <a class="btn btn-small btn-success" href="<?php echo WWWROOT; ?>admin/index/index/save">Novo Post</a>
    </div>
</div>
<div class="row">
    <div class="span12">
        <table class="table table-condensed table-bordered">
            <tbody>
                <tr style="background-color: #DFF0D8; font-weight: bold;">
                    <td>Título</td>
                    <td>Data</td>
                    <td colspan="2">Conteúdo</td>
                </tr>
                <?php foreach ($posts as $post) { ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($post['title']); ?></td>
                        <td><?php echo $this->formatarData($post['post_date']); ?></td>
                        <td><?php echo $this->escapeHtml(substr($post['description'], 0, 150)); ?></td>
                        <td style="width: 90px;">
                            <a href="<?php echo WWWROOT; ?>admin/index/index/save/id/<?php echo $post['id']; ?>" class="btn-link">Editar</a> |
                            <a href="<?php echo WWWROOT; ?>admin/index/index/delete/id/<?php echo $post['id']; ?>" class="btn-link">Excluir</a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="span12">
            <?php echo $this->paginationControl($posts, 'Sliding', 'partials/paginator/control.phtml'); ?>
        </div>
    </div>
</div>


