<script type="text/javascript" src="<?php echo WWWROOT;?>tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea"
    });
</script>

<div class="row">
    <div class="span12">
        <h2>Editando Post</h2>
    </div>
</div>
<div class="row">
    <div class="span12">
        <?php
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
        ?>
    </div>
</div>