<div class="row">
    <div class="span9">
        <h3><span class="zf-green" >Formulário de contato</span></h3>
        <?php
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
        ?>

    </div>
    <div class="span3">
        <h2>Últimos posts</h2>
        <?php foreach ($demaisPosts as $post) { ?>
            <blockquote>
                <h3><a href="<?= WWWROOT ?>detalhe/<?php echo urlencode($post['title']); ?>-<?php echo $post['id']; ?>"><span class="zf-green" ><?php echo $post['title']; ?></span></a></h3>
                <small><?php echo $this->formatarData($post['post_date']); ?></small>
            </blockquote>

        <?php } ?> 

        <?php echo $this->paginationControl($demaisPosts, 'Sliding', 'partials/paginator/control.phtml'); ?>

    </div>
</div>
