<div class="row">
    <?php foreach ($posts as $post) { ?>
        <div class="span8">
            <blockquote>
                <h3><a href="<?=WWWROOT?>detalhe/<?php echo urlencode($post['title']); ?>-<?php echo $post['id']; ?>"><span class="zf-green" ><?php echo $post['title']; ?></span></a></h3>
                <small><?php echo $this->formatarData($post['post_date']); ?></small>
            </blockquote>
        </div>
        
    <?php } ?>
</div>

<div class="row">
    <div class="span12">
        <?php echo $this->paginationControl($posts, 'Sliding', 'partials/paginator/control.phtml'); ?>
    </div>
</div>
